### ISSUE TITLE
build of linux package hanging?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/statsd-feedstock#3]
Seeing a fail on the master build:
https://circleci.com/gh/conda-forge/statsd-feedstock/6

Similar to this: https://github.com/conda-forge/cfchecker-feedstock/issues/7
```
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git command i returned 128: 
```

**Comment by bollwyvl** [comment]
It's odd that this didn't happen on the two PR builds for #2... I wonder if it's just a matter of resetting the key?

**Comment by ericdill** [comment]
@bollwyvl @ocefpaf did this get resolved? I'm seeing the same issue on the [spefile master branch build](https://circleci.com/gh/conda-forge/spefile-feedstock/24)

cc @jschueller

**Comment by bollwyvl** [comment]
Looks like linux-64 builds are building:
https://anaconda.org/conda-forge/statsd/files?version=3.2.2
